In [1]:
import pandas as pd

In [2]:
df = pd.read_parquet("../data/raw/oiseaux-france.parquet")

In [3]:
df.head(3)

,class,order,family,genus,species,scientificName,decimalLatitude,decimalLongitude,coordinateUncertaintyInMeters,elevation,eventDate,month,year,speciesKey,recordedBy
0,Aves,Charadriiformes,Recurvirostridae,Recurvirostra,Recurvirostra avosetta,"Recurvirostra avosetta Linnaeus, 1758",43.35635,4.81863,250.0,2.0,2020-09-30,9.0,2020,2480259.0,MéZENGE François
1,Aves,Charadriiformes,Laridae,Hydroprogne,Hydroprogne caspia,"Hydroprogne caspia (Pallas, 1770)",43.35635,4.81863,250.0,1.0,2020-09-08,9.0,2020,2481236.0,BLASCO André
2,Aves,Passeriformes,Certhiidae,Certhia,Certhia brachydactyla,"Certhia brachydactyla C.L.Brehm, 1820",43.71169,5.07810,250.0,112.0,2020-02-20,2.0,2020,7806848.0,FLITTI Amine

In [4]:
df["speciesKey"] = df["speciesKey"].astype("category")
df["species"].value_counts()

species
Fringilla coelebs           233761
Erithacus rubecula          216847
Turdus merula               215123
Parus major                 197240
Sylvia atricapilla          175853
                             ...
Tringa brevipes                  1
Leucopternis schistaceus         1
Spinus pinus                     1
Loxia leucoptera                 1
Spizella passerina               1
Name: count, Length: 585, dtype: int64

In [5]:
mapping = pd.read_csv("../data/processed/taxref_species_vernacular_mapping.csv")

df = df.merge(mapping, on="species", how="left")

In [6]:
df.head()

,class,order,family,genus,species,scientificName,decimalLatitude,decimalLongitude,coordinateUncertaintyInMeters,elevation,eventDate,month,year,speciesKey,recordedBy,vernacularName_fr
0,Aves,Charadriiformes,Recurvirostridae,Recurvirostra,Recurvirostra avosetta,"Recurvirostra avosetta Linnaeus, 1758",43.35635,4.81863,250.0,2.0,2020-09-30,9.0,2020,2480259.0,MéZENGE François,Avocette élégante
1,Aves,Charadriiformes,Laridae,Hydroprogne,Hydroprogne caspia,"Hydroprogne caspia (Pallas, 1770)",43.35635,4.81863,250.0,1.0,2020-09-08,9.0,2020,2481236.0,BLASCO André,Sterne caspienne
2,Aves,Passeriformes,Certhiidae,Certhia,Certhia brachydactyla,"Certhia brachydactyla C.L.Brehm, 1820",43.71169,5.07810,250.0,112.0,2020-02-20,2.0,2020,7806848.0,FLITTI Amine,Grimpereau des jardins
3,Aves,Passeriformes,Fringillidae,Carduelis,Carduelis carduelis,"Carduelis carduelis (Linnaeus, 1758)",43.06400,5.85255,250.0,24.0,2020-04-20,4.0,2020,2494686.0,ZWANK Aline,Chardonneret élégant
4,Aves,Passeriformes,Emberizidae,Emberiza,Emberiza calandra,"Emberiza calandra Linnaeus, 1758",43.63410,6.37685,25.0,634.0,2020-10-24,10.0,2020,7634625.0,SPAETH Estelle,Bruant proyer

In [7]:
df.loc[df["family"] == "Phasianidae", "species"].unique()

array(['Phasianus colchicus', 'Alectoris rufa', 'Coturnix coturnix',
       'Perdix perdix', 'Pavo cristatus', 'Syrmaticus reevesii',
       'Lyrurus tetrix', 'Lagopus muta', 'Alectoris graeca',
       'Tetrastes bonasia', None, 'Chrysolophus pictus',
       'Tetrao urogallus', 'Gallus gallus', 'Lagopus lagopus'],
      dtype=object)

In [8]:
df.loc[df["family"] == "Phasianidae"] \
  .groupby("species") \
  .size() \
  .sort_values(ascending=False)

species
Alectoris rufa         25627
Phasianus colchicus    21420
Coturnix coturnix       9223
Lyrurus tetrix          6050
Perdix perdix           4597
Lagopus muta            3189
Alectoris graeca        2401
Tetrastes bonasia        434
Pavo cristatus           273
Syrmaticus reevesii      251
Tetrao urogallus          29
Gallus gallus             10
Chrysolophus pictus        5
Lagopus lagopus            1
dtype: int64

In [9]:
df2 = pd.read_csv("../data/processed/phasianidae_oso.csv")

In [10]:
df2.head()

,class,order,family,genus,species,scientificName,decimalLatitude,decimalLongitude,coordinateUncertaintyInMeters,elevation,eventDate,month,year,speciesKey,recordedBy,geometry,oso_2024,code,label_fr,label_en
0,Aves,Galliformes,Phasianidae,Phasianus,Phasianus colchicus,"Phasianus colchicus Linnaeus, 1758",43.53726,4.76251,250.0,2.0,2020-09-05,9.0,2020,9752149.0,PAUMIER Jean-Marc,POINT (4.76251 43.53726),23,23.0,Eau,Water
1,Aves,Galliformes,Phasianidae,Phasianus,Phasianus colchicus,"Phasianus colchicus Linnaeus, 1758",43.19204,6.10492,25.0,49.0,2020-06-03,6.0,2020,9752149.0,LASTèRE Irène,POINT (6.10492 43.19204),17,17.0,Forêt de conifères,Softwood forest
2,Aves,Galliformes,Phasianidae,Alectoris,Alectoris rufa,"Alectoris rufa (Linnaeus, 1758)",43.48183,5.31699,250.0,128.0,2020-11-12,11.0,2020,2474051.0,PELISSIE Mathieu,POINT (5.31699 43.48183),16,16.0,Forêt de feuillus,Hardwood forest
3,Aves,Galliformes,Phasianidae,Phasianus,Phasianus colchicus,"Phasianus colchicus Linnaeus, 1758",43.66428,5.20037,25.0,148.0,2020-02-28,2.0,2020,9752149.0,MAISONGRANDE Frédéric,POINT (5.20037 43.66428),2,2.0,Zone urbaine diffuse,Diffuse built-up area
4,Aves,Galliformes,Phasianidae,Phasianus,Phasianus colchicus,"Phasianus colchicus Linnaeus, 1758",43.58015,4.88762,250.0,29.0,2020-03-15,3.0,2020,9752149.0,JAFFRE Jonathan,POINT (4.88762 43.58015),14,14.0,Vergers,Orchards and fruit growing

In [11]:
df2.dtypes

class                             object
order                             object
family                            object
genus                             object
species                           object
scientificName                    object
decimalLatitude                  float64
decimalLongitude                 float64
coordinateUncertaintyInMeters    float64
elevation                        float64
eventDate                         object
month                            float64
year                               int64
speciesKey                       float64
recordedBy                        object
geometry                          object
oso_2024                           int64
code                             float64
label_fr                          object
label_en                          object
dtype: object

In [12]:
from shapely import wkt
import geopandas as gpd

df2["geometry"] = df2["geometry"].apply(wkt.loads)

In [13]:
gdf = gpd.GeoDataFrame(
    df2,
    geometry="geometry",
    crs="EPSG:4326"   # important si coords GPS
)

In [14]:
type(gdf)
#gdf.crs

geopandas.geodataframe.GeoDataFrame

In [15]:
departements = gpd.read_file("../data/shp/departements-20170102.shp", encoding="utf-8")

print(departements.head())
print(departements.crs)

  code_insee          nom  nuts3                 wikipedia wikidata   surf_ha  \
0         43  Haute-Loire  FR723            fr:Haute-Loire   Q12572  500360.0
1         63  Puy-de-Dôme  FR724            fr:Puy-de-Dôme   Q12694  801543.0
2         12      Aveyron  FR622  fr:Aveyron (département)    Q3216  877339.0
3         48       Lozère  FR814   fr:Lozère (département)   Q12580  517505.0
4         81         Tarn  FR627     fr:Tarn (département)   Q12772  578240.0

                                            geometry
0  POLYGON ((3.10396 45.35483, 3.10952 45.35276, ...
1  POLYGON ((2.56631 46.14312, 2.57259 46.14171, ...
2  POLYGON ((2.20708 44.61593, 2.21039 44.6186, 2...
3  POLYGON ((2.98226 44.64515, 2.98563 44.65011, ...
4  POLYGON ((1.99027 44.14953, 1.99653 44.15103, ...
EPSG:4326

In [16]:
gdf_dep = gpd.sjoin(
    gdf,
    departements[["nom", "code_insee", "geometry"]],
    how="left",
    predicate="within"
)

In [17]:
gdf_dep.head()

,class,order,family,genus,species,scientificName,decimalLatitude,decimalLongitude,coordinateUncertaintyInMeters,elevation,...,speciesKey,recordedBy,geometry,oso_2024,code,label_fr,label_en,index_right,nom,code_insee
0,Aves,Galliformes,Phasianidae,Phasianus,Phasianus colchicus,"Phasianus colchicus Linnaeus, 1758",43.53726,4.76251,250.0,2.0,...,9752149.0,PAUMIER Jean-Marc,POINT (4.76251 43.53726),23,23.0,Eau,Water,99.0,Bouches-du-Rhône,13
1,Aves,Galliformes,Phasianidae,Phasianus,Phasianus colchicus,"Phasianus colchicus Linnaeus, 1758",43.19204,6.10492,25.0,49.0,...,9752149.0,LASTèRE Irène,POINT (6.10492 43.19204),17,17.0,Forêt de conifères,Softwood forest,96.0,Var,83
2,Aves,Galliformes,Phasianidae,Alectoris,Alectoris rufa,"Alectoris rufa (Linnaeus, 1758)",43.48183,5.31699,250.0,128.0,...,2474051.0,PELISSIE Mathieu,POINT (5.31699 43.48183),16,16.0,Forêt de feuillus,Hardwood forest,99.0,Bouches-du-Rhône,13
3,Aves,Galliformes,Phasianidae,Phasianus,Phasianus colchicus,"Phasianus colchicus Linnaeus, 1758",43.66428,5.20037,25.0,148.0,...,9752149.0,MAISONGRANDE Frédéric,POINT (5.20037 43.66428),2,2.0,Zone urbaine diffuse,Diffuse built-up area,99.0,Bouches-du-Rhône,13
4,Aves,Galliformes,Phasianidae,Phasianus,Phasianus colchicus,"Phasianus colchicus Linnaeus, 1758",43.58015,4.88762,250.0,29.0,...,9752149.0,JAFFRE Jonathan,POINT (4.88762 43.58015),14,14.0,Vergers,Orchards and fruit growing,99.0,Bouches-du-Rhône,13

In [18]:
mapping = pd.read_csv("../data/processed/taxref_species_vernacular_mapping.csv")

gdf_dep = gdf_dep.merge(mapping, on="species", how="left")

In [19]:
gdf_dep.head()

,class,order,family,genus,species,scientificName,decimalLatitude,decimalLongitude,coordinateUncertaintyInMeters,elevation,...,recordedBy,geometry,oso_2024,code,label_fr,label_en,index_right,nom,code_insee,vernacularName_fr
0,Aves,Galliformes,Phasianidae,Phasianus,Phasianus colchicus,"Phasianus colchicus Linnaeus, 1758",43.53726,4.76251,250.0,2.0,...,PAUMIER Jean-Marc,POINT (4.76251 43.53726),23,23.0,Eau,Water,99.0,Bouches-du-Rhône,13,Faisan de Colchide
1,Aves,Galliformes,Phasianidae,Phasianus,Phasianus colchicus,"Phasianus colchicus Linnaeus, 1758",43.19204,6.10492,25.0,49.0,...,LASTèRE Irène,POINT (6.10492 43.19204),17,17.0,Forêt de conifères,Softwood forest,96.0,Var,83,Faisan de Colchide
2,Aves,Galliformes,Phasianidae,Alectoris,Alectoris rufa,"Alectoris rufa (Linnaeus, 1758)",43.48183,5.31699,250.0,128.0,...,PELISSIE Mathieu,POINT (5.31699 43.48183),16,16.0,Forêt de feuillus,Hardwood forest,99.0,Bouches-du-Rhône,13,Perdrix rouge
3,Aves,Galliformes,Phasianidae,Phasianus,Phasianus colchicus,"Phasianus colchicus Linnaeus, 1758",43.66428,5.20037,25.0,148.0,...,MAISONGRANDE Frédéric,POINT (5.20037 43.66428),2,2.0,Zone urbaine diffuse,Diffuse built-up area,99.0,Bouches-du-Rhône,13,Faisan de Colchide
4,Aves,Galliformes,Phasianidae,Phasianus,Phasianus colchicus,"Phasianus colchicus Linnaeus, 1758",43.58015,4.88762,250.0,29.0,...,JAFFRE Jonathan,POINT (4.88762 43.58015),14,14.0,Vergers,Orchards and fruit growing,99.0,Bouches-du-Rhône,13,Faisan de Colchide

In [20]:
ep_sig = gpd.read_file("../data/shp/sig_metrop.shp", encoding="utf-8")
# si accents cassés: encoding="latin1"

In [21]:
ep_site = pd.read_csv("../data/raw/ep_site.csv", sep=";", encoding="utf-8")
# adapte sep="," si besoin

In [22]:
liste_des = pd.read_csv("../data/raw/liste_designations.csv", sep=";", encoding="utf-8")

In [25]:
liste_des.head()

,id_designation,id_designation_sup,lb_designation,abr_designation_sig,type_protection
0,02,NaN,Géoparcs mondiaux UNESCO,geoparc,Protection au titre d'une convention ou d'un p...
1,03,NaN,Arrêté listes de sites d'intérêt géologique,aplg,Protection réglementaire
2,04,NaN,Zone de protection renforcée d'une réserve nat...,zpr,NaN
3,08,NaN,Grand Site de France,gsf,NaN
4,09,NaN,Projet de Grand Site de France,pgsf,NaN

In [26]:
ep = ep_sig.merge(ep_site, on="cd_sig", how="left")

In [27]:
ep = ep.merge(liste_des, on="id_designation", how="left")

In [28]:
ep.columns

Index(['cd_sig', 'id_mnhn_x', 'territoire', 'sup_ha', 'sup_ter_ha',
       'sup_mer_ha', 'milieu', 'ref_nom', 'ref_vers', 'ech_num', 'proj',
       'geometry', 'id_ep_site', 'id_mnhn_y', 'id_designation', 'pid_mnhn',
       'id_local', 'id_inspire', 'id_natda_wdpa', 'nom', 'nom_complet',
       'superficie_ha_textoff', 'superficie_ha_textautre', 'categorie_uicn',
       'rb_mixte', 'enjeu', 'proc_creation', 'date_crea_sign',
       'date_modif_geo', 'date_crea_publi', 'proc_dern_modif',
       'type_dern_modif', 'date_dern_modif_sign', 'date_dern_modif_publi',
       'date_fin_valid', 'gestionnaire', 'operateur', 'commentaire',
       'id_designation_sup', 'lb_designation', 'abr_designation_sig',
       'type_protection'],
      dtype='object')

In [29]:
print(ep.head().to_string())

          cd_sig  id_mnhn_x territoire     sup_ha  sup_ter_ha  sup_mer_ha milieu         ref_nom ref_vers  ech_num  proj                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        

In [30]:
# Harmoniser CRS
ep = ep.to_crs(gdf_dep.crs)

In [31]:
j = gpd.sjoin(
    gdf_dep[["geometry"]],             # on ne garde que la géométrie côté gauche
    ep[["cd_sig", "nom", "lb_designation","abr_designation_sig","categorie_uicn", "geometry"]],  # adapte "nom"/"designation"
    how="left",
    predicate="within"  # ou "intersects" si points sur frontières
)

In [32]:
in_ep = j["index_right"].notna().groupby(level=0).any()
gdf_dep["in_ep"] = gdf_dep.index.to_series().map(in_ep).fillna(False)

In [33]:
names = (
    j.dropna(subset=["nom"])
     .groupby(level=0)["nom"]
     .apply(lambda s: "; ".join(sorted(set(map(str, s)))))
)
gdf_dep["ep_names"] = gdf_dep.index.to_series().map(names)

In [34]:
types_ = (
    j.dropna(subset=["lb_designation"])
     .groupby(level=0)["lb_designation"]
     .apply(lambda s: "; ".join(sorted(set(map(str, s)))))
)
gdf_dep["ep_types"] = gdf_dep.index.to_series().map(types_)

In [35]:
types_abr = (
    j.dropna(subset=["abr_designation_sig"])
     .groupby(level=0)["abr_designation_sig"]
     .apply(lambda s: "; ".join(sorted(set(map(str, s)))))
)
gdf_dep["ep_types_abr"] = gdf_dep.index.to_series().map(types_abr)

In [36]:
gdf_dep["in_ep"].value_counts(dropna=False)
gdf_dep.loc[gdf_dep["in_ep"], "ep_names"].head(10)

0         Camargue; Camargue (Delta Du Rhône)
2                          Massif De L'Arbois
5                          Massif De L'Arbois
6                             Préalpes D’Azur
9                            Catalany; Verdon
10                           Catalany; Verdon
11        Camargue; Camargue (Delta Du Rhône)
17    Unesco Global Geoparc De Haute-Provence
18                                     Verdon
20                  Camargue (Delta Du Rhône)
Name: ep_names, dtype: object

In [37]:
print(gdf_dep.head().to_string())

  class        order       family      genus              species                      scientificName  decimalLatitude  decimalLongitude  coordinateUncertaintyInMeters  elevation   eventDate  month  year  speciesKey             recordedBy                  geometry  oso_2024  code              label_fr                    label_en  index_right               nom code_insee   vernacularName_fr  in_ep                             ep_names                                                                                                    ep_types       ep_types_abr
0  Aves  Galliformes  Phasianidae  Phasianus  Phasianus colchicus  Phasianus colchicus Linnaeus, 1758         43.53726           4.76251                          250.0        2.0  2020-09-05    9.0  2020   9752149.0      PAUMIER Jean-Marc  POINT (4.76251 43.53726)        23  23.0                   Eau                       Water         99.0  Bouches-du-Rhône         13  Faisan de Colchide   True  Camargue; Camargue (Delta Du Rhône)  Parc naturel régional; Réserve de Biosphère, zone tampon; Zone humide protégée par la convention de Ramsar  bios; pnr; ramsar
1  Aves  Galliformes  Phasianidae  Phasianus  Phasianus colchicus  Phasianus colchicus Linnaeus, 1758         43.19204           6.10492                           25.0       49.0  2020-06-03    6.0  2020   9752149.0          LASTèRE Irène  POINT (6.10492 43.19204)        17  17.0    Forêt de conifères             Softwood forest         96.0               Var         83  Faisan de Colchide  False                                  NaN                                                                                                         NaN                NaN
2  Aves  Galliformes  Phasianidae  Alectoris       Alectoris rufa     Alectoris rufa (Linnaeus, 1758)         43.48183           5.31699                          250.0      128.0  2020-11-12   11.0  2020   2474051.0       PELISSIE Mathieu  POINT (5.31699 43.48183)        16  16.0     Forêt de feuillus             Hardwood forest         99.0  Bouches-du-Rhône         13       Perdrix rouge   True                   Massif De L'Arbois                                                                            Site classé selon la loi de 1930                 sc
3  Aves  Galliformes  Phasianidae  Phasianus  Phasianus colchicus  Phasianus colchicus Linnaeus, 1758         43.66428           5.20037                           25.0      148.0  2020-02-28    2.0  2020   9752149.0  MAISONGRANDE Frédéric  POINT (5.20037 43.66428)         2   2.0  Zone urbaine diffuse       Diffuse built-up area         99.0  Bouches-du-Rhône         13  Faisan de Colchide  False                                  NaN                                                                                                         NaN                NaN
4  Aves  Galliformes  Phasianidae  Phasianus  Phasianus colchicus  Phasianus colchicus Linnaeus, 1758         43.58015           4.88762                          250.0       29.0  2020-03-15    3.0  2020   9752149.0        JAFFRE Jonathan  POINT (4.88762 43.58015)        14  14.0               Vergers  Orchards and fruit growing         99.0  Bouches-du-Rhône         13  Faisan de Colchide  False                                  NaN                                                                                                         NaN                NaN