In [4]:
import pandas as pd

In [ ]:
df = pd.read_parquet("oiseaux-france.parquet")

scientificName
Lyrurus tetrix (Linnaeus, 1758)    5558
Tetrao tetrix Linnaeus, 1758        492
Name: count, dtype: int64

In [6]:
df.head(3)

,class,order,family,genus,species,scientificName,decimalLatitude,decimalLongitude,coordinateUncertaintyInMeters,elevation,eventDate,month,year,speciesKey,recordedBy
0,Aves,Charadriiformes,Recurvirostridae,Recurvirostra,Recurvirostra avosetta,"Recurvirostra avosetta Linnaeus, 1758",43.35635,4.81863,250.0,2.0,2020-09-30,9.0,2020,2480259.0,MéZENGE François
1,Aves,Charadriiformes,Laridae,Hydroprogne,Hydroprogne caspia,"Hydroprogne caspia (Pallas, 1770)",43.35635,4.81863,250.0,1.0,2020-09-08,9.0,2020,2481236.0,BLASCO André
2,Aves,Passeriformes,Certhiidae,Certhia,Certhia brachydactyla,"Certhia brachydactyla C.L.Brehm, 1820",43.71169,5.07810,250.0,112.0,2020-02-20,2.0,2020,7806848.0,FLITTI Amine

In [11]:
df["speciesKey"] = df["speciesKey"].astype("category")
df["species"].value_counts()

species
Fringilla coelebs           233761
Erithacus rubecula          216847
Turdus merula               215123
Parus major                 197240
Sylvia atricapilla          175853
                             ...
Tyto furcata                     1
Leucopternis schistaceus         1
Spinus pinus                     1
Loxia leucoptera                 1
Spizella passerina               1
Name: count, Length: 585, dtype: int64

In [14]:
mapping = pd.read_csv("taxref_species_vernacular_mapping.csv")

df = df.merge(mapping, on="species", how="left")

In [15]:
df.head()

,class,order,family,genus,species,scientificName,decimalLatitude,decimalLongitude,coordinateUncertaintyInMeters,elevation,eventDate,month,year,speciesKey,recordedBy,vernacularName_fr
0,Aves,Charadriiformes,Recurvirostridae,Recurvirostra,Recurvirostra avosetta,"Recurvirostra avosetta Linnaeus, 1758",43.35635,4.81863,250.0,2.0,2020-09-30,9.0,2020,2480259.0,MéZENGE François,Avocette élégante
1,Aves,Charadriiformes,Laridae,Hydroprogne,Hydroprogne caspia,"Hydroprogne caspia (Pallas, 1770)",43.35635,4.81863,250.0,1.0,2020-09-08,9.0,2020,2481236.0,BLASCO André,Sterne caspienne
2,Aves,Passeriformes,Certhiidae,Certhia,Certhia brachydactyla,"Certhia brachydactyla C.L.Brehm, 1820",43.71169,5.07810,250.0,112.0,2020-02-20,2.0,2020,7806848.0,FLITTI Amine,Grimpereau des jardins
3,Aves,Passeriformes,Fringillidae,Carduelis,Carduelis carduelis,"Carduelis carduelis (Linnaeus, 1758)",43.06400,5.85255,250.0,24.0,2020-04-20,4.0,2020,2494686.0,ZWANK Aline,Chardonneret élégant
4,Aves,Passeriformes,Emberizidae,Emberiza,Emberiza calandra,"Emberiza calandra Linnaeus, 1758",43.63410,6.37685,25.0,634.0,2020-10-24,10.0,2020,7634625.0,SPAETH Estelle,Bruant proyer